export const MODAL = {
  SET_CONTENT: "SET_CONTENT",
  TOGGLE_MODAL: "TOGGLE_MODAL"
};

export const PRODUCTS = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS", 
  TOGGLE_ADDED_ITEM: "TOGGLE_ADDED_ITEM",
  TOGGLE_LIKED_ITEM: "TOGGLE_LIKED_ITEM",
  RESET_ADDED_ITEMS: "RESET_ADDED_ITEMS"
}